language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- '6'
branches:
  only:
  - master
  - travis-test
before_script:
- npm install
after_success:
- git config --global user.email "remy.trompier@gmail.com"
- git config --global user.name "rtrompier"
- npm run deploy
env:
  global:
  - secure: ixeco2d/OrmCem/pC06oaOCq/mmHujhCU1RIj2kVqbZpj2C2pgS/6tIJe6Ximy7k5r3pPE9qqcaUzK9ur3oZ1MGUrSvI/c2S4Ylg38Bdi7aJPXqZWN+kCFNrzcBDOwFGhIgOwzrwwrut3+hhsv0aHBQXSDfSygFg41umsWdLZJ5TswEYRZFQWgGQ7lWt4N4Z3ctdBEAx5tYO9aGR40c9cm5Gwdb5fB6A5MB+xyouMWfRUL1pTICQbemGPN0vk/vDkUzk27XuK8/GmmSLRy5vUi9YhBse1iNnQrbkU3vEv2X7X49gX8T88GB0bkQRBQMrKRKbUjkgiTNL/lY/SNaQmHXf0MePT5Bti8Ooadv+/uaRCc05dD+H6tQWL7JIbMCVN+2Ha1RkCUdhu0ZRdhfgpaFk8SBihUwrcrt+JTzRxQD1IZedG3+6seUCWjbTiXLWbHAbQinFaC308ylLC/z6fANT4XNkGWAgpp4nGvo8H51IWD+UO2vaQR6lalrW1GzDfCP/oJSUK9ZSRrQ24dQutJnfspaErcf+xtQ+gQrX4kU4EqfUsTRvLkziPPY+XYUvDqxtxy4ZPVjOeOisFmgxVzKMwoHypI/F986PESbG2/2LPI63lPxKlSiybDTU0puicBJhyJPibfmE96Q24NF596d+gBh0mPryrNmmuIO+YW8=
  - secure: N/DKhdIm0igYLkJv5rHA2wRZ5qbwT4Fnhj7bEs0CR05miMi9eaW5uE9ATEKI1uzWz/IAACANBcp0U7KLylDwBpTRJ8thhaUufllJlKJBXK4ZCi1VS12mVBsXu+DfCqltBDdJh7FccdGLNHG6tBk5bv+UutclmWJhlhgZ09szRjqHP/qNmyyRnchzGQpySH269CmitSO7wCSOT7/pVnwzqQ9RsitRw0UMAG1L8ZPMKoZ9wCkfzFpEhvUC7Y4INeqEyvvvO0qcvnTCdxbVAT0UGaDVkLPdfN5fzPqtVHE7F/xP/xoHNzL8lNz2dZHbVUY2e8MPtqhQiakLTeN/DthJRi1gQUjW8lrX5iYT3kIXfJeSW/oKRKNSrFHqOd1SfSlw0qi/XjOj7bEtdqgYrMjuwGHj4UBQ+iu96eI7Q42Mbx8KHpZ9jDSPgHj4YRm4pp71okMFDqCREyixTi3tsLfXgQU1lvWnvytc5XUe+8EhZ0402Fs3jUz9igj45i8y/oKZgbsqm1mBbYdrTEAjUOFWXVCs8YFs3eIhODN0wqWFT5RD896qoq8M5c7bEfovyE9mE1y6wQNIcAMBlMqcN9UUp+jMhNeqzAORJgYGgeuP1kX7sBLRrLqSLuiS7rdz/fcauo0zTTf+uiLt9pCXr9cmQ55NjSpaklUZkrEdKCrlHAs=
