language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- '6'
branches:
  only:
  - master
  - travis-test
before_script:
- npm install
after_success:
- git config --global user.email "remy.trompier@gmail.com"
- git config --global user.name "rtrompier"
- npm run deploy
env:
  global:
    secure: J3ft1LeJa03M6fIq3LEAH8Vfz3U4Wrhad1snHZrMmIelCtN10HW4ZLgrytSsG6FA1DDOg1UygxZcDC56XEYEZkeDBfE8APaaInIZhXOPt0LGRCYsX/Sbgsl3YY7/CGufjoe6FSVLMxaplO05SrtcL63jaLASlBZfDhSQvZ7kAKJLZQdhka+2FwhKW1rslxTMLrFQtSRK1K0l6UWqoIGdyuKxiS0xS4e6Tq5q6PY6qh1e6roOSz/Ii1NCz/79QRdrHS0N5XAUCs6BmMWwKLLPZO2k8QowiEl8B2gARjkWvQpzhLOJJYGNvqX6WBzXzF17QDbIZ5rOPlQDNFvw61p3/NTjK7wLdzFooqQVlMwAvrmdlz89Vbh81oUTbY2tqGjUm9WkfELu/eAowViwG6DaccUXguKgYEi65IVaY/1PsfR+NkeDZKzog4rsjrVppv5jCYYUxN7HgHdAip6Ksn5GuKZc/N6wvuekQd7E5jXDseuKjAuF77sT31wW1I42tbUK7VhZ0HUNekeNBJ9m5/q18btMrS8wsapUKCBVbjL7WTMJXvjKOT4yNfa+xHpxYP5+P+gVCXWqqgPVYLSZ/7B/u6+fTLH56PscirW5CjEK1RudkWxvg7OPp2T46nsD7SX9yvtkwoOWYbBumW0UEt/DFr5lklvb83OkJ42pOzI41yU=
