language: node_js
node_js:
- '6'
deploy: 
api_key: 
email: gmer@hcuge.ch
provider: npm
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm publish . --access=public
env:
  global:
    secure: eqv2Q1peGXC+h6ybMmlPa1BmEfMVIOMLeoEZbQ+qgNAQUeEhZcOHx6zqk5HH2+jwDwhfZSdW5bK/Z7vDor13rbatVCewoy82+oqcBWe71rXb9NUMimO+Me4h9d8iWRsirlzo2ct3KGdwxVdzAJ+ZxFL0WPXv7akNkIkxy1Xga0fowp4snixotzmd35KioNhvHmgOGvZRnhnrgaY7MzfJKoKBSCQpkARhz1rrZ2EU0V0gKrP87W5C/rYCCl6k17B30VyGWpB/M2QgBpRv2muqEMqzmJBRrV/JaoI734TTVBV2LyK6a+Et5BWSNR0gYy3I8SFE1RLu01OjHl3adqyAfB68PxAV0EiUXU+kJGlnj3ym5O/S874sgr9QnMv4+ZNpfR0l+AyikV4ZBT5bJe1sxxaPyuJXwZuiNQafTXE1XCtoFhoyEyT8smKFeXWNvhbUbvxY3AnTmpDkYazwsZbwUYTlq2DXVwk3mWg9gc2DUIOhyXRr18e6utf3cul/vyCWwX0fiQhfkWzANUNPjv0GBDKLUB7JndqRXB4lijniQEWrPdDwmCZ/HucSGGeQljQQSZbeFrSpeCmqDyPsXATfrUK1ckns9B8qfR13zPO6Gttw5kI2Jw1rkjxERkDeuGFtbkdNrjP3B24igJwAQmboe90lqvCkduIqMw2TzesSnKA=
