language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
branches:
  only:
    - master
    - travis-test
before_script:
  - npm install
after_success:
  - npm run deploy
  - npm run publish