language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- stable
branches:
  only:
  - master
  - travis-test
before_script:
- npm prune
after_success:
- git config --global user.email "remy.trompier@gmail.com"
- git config --global user.name "rtrompier"
- npm run deploy