language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- stable
branches:
  only:
  - master
  - travis-test
before_script:
- npm prune
after_success:
- npm run deploy
deploy:
  provider: npm
  email: gmer@hcuge.ch
  api_key:
    secure: qW5srlnj3UiSkQGwUv07NfyQ18Ry9emfqUXKroDuRr7q5Ip5GJ3DUGoJYJLRehHjT98YSHwUBhW9VvEgI4SopX8SMr4mPyRqU/uUL8IAcJH3kgzsBD2laDf/MPraGHOD3vg4ILZDjMWZaRmfAp2Wr2316OWiTEYGRyK7SmYH5FjLiV6NT1Iif11kRCfZKTb7HXzkldJ8kQ2zocLmihURGobRo7E4eMeYlqA+KNQkzMxcYf1SaJW8uYbWlhDY3DhyBTtMZUUV9qcH4nJ0lVGqlVpaR/+FM53pDRNlViqFZJTpvfYD8kArBjz4XF3memzd5OoG3S5+ZtjYJcUDcRPHJHqugGYFilMSdfzgol28HQlgDCaTTmA2ISOEYkxMhyqBL6LzzoHKC386eA2UbZFWYbRqx1RadDFJjAerLP4VLrOrDZOIOtrORHuFUXE8qmKW5ECSpb4W3bT3QuUr6qePTZ3jIcq31jfP317sWAjEYMMDZF4EykeaGTv6smaGdXyq5byjnfXCwzQzV8OPOwYNGTMnzWuEEU5hK/URWW1XzShxtSsnvMXP+JP8oYdJl83xSmNQJgs3aradk6LL6uI3VDcz9qnbNBJeW/uUCLBU/xPaEO65WtLeG54QbKA8oxjueRWmIAg/hiYm/N+vQaPV5mqN57D1r80b85HBgybMvfs=
  on:
    repo: DSI-HUG/dejajs-components
    branch: travis-test
