dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
  sonarcloud:
    organization: "hug-dsi"
    token:
      secure: "U0zTbKggAYZWFh3srcotXs89DQoB4zG+Mqw8eMl2hRn1Jk/7pbAxLrlC+7rNU63WJcULN+Rot7QpM1mzyCNIfHmFQUTDJTBEYr+NT7q/NPrriGx/PNGQGeSGA4QDdN1EXckTyuFUPC/vd99i3ElGKuq/ZlTWy4nS5I9KB21RR0sk8laRo6kTKoPBQtI6Ou4Y4vzPzS3viZCoKcJOr/yj6k2SQ7FFbTABJn/bA113pSkgxXsJsUdZx6ld42y8NH/3E+O8cwUwUzvuR/PTtMjFG3RNzrkL5aHYys6hcXx4a6CsBAayUgmCFTrGkHcMf5S55i5RiOSTOi81zR6Rh0D+pSYXtfH0NbHK7z1DvP9nSVJ2UUVMRcsNeo7vSkRZTpUHKcADvj8oMHwMSI1iOgstAhoBkU9Lp1eQE8591MZWk2SPW0gYtMFiDwOv9kHaG/wsA1bqjEEAPTqk0Z3P9VhtzXBgv6iZU4bWvRaNCjYR8PAqIQFO3rfY6b3JPpnClyfxaG5CZ/8j1zJT73sztMd4TIXue9sKReR+59HESXGFkknmKAovvH1g7GRieJvIKRdh8Am0VNxM8o5aJNm7WRwuADGLSMNJ1MQtdLJmU8Uct0YLtRu4O0hNZIBaXafZJnSVFZMMhGDoAii+A17hUQE1AhBCjZwQm14tn2DybUBctEU="
    github_token:
      secure: "Q3c1QvywMZ4VyPof/esv9sNanHC+kjMFUr5PY8Fxc2eATePBKYNW+IsCydGGXnXupvfKj48xDzj9I1tHis0Qlc10/vHs1AhQDlebJlG7NWEdOlNiJ1XTi8XN0rrryL7NFEjRlALCVDaqeF3SldtmGH1Wg2SLzjBui4/xtCaif7qWGFld3V0Hr7qXF+r1ktT86R9P7Vwyqemb9CdTpbwS8bxJW9q9uIhL24JV4aRfamZlVDgfPT1dhw9jSOTsYUI8+eDmmpdpHdoHmDYSxyJ6QQFsY4Mw15BQ6qy4QyELr7gVnZEiMiEeSSZ5vhIQsvSlDltc/KBe3vwqRljC1XilgdxRuC9kTiQnCxMnX5aM6iZ0m33OAuGGtPji4siO1641TH/dbSdsFfEmWMepDtB0xTt7kpZpT8X64jA+NnWbg7kGcbDPHvyrnZHYg0EiDss1pIotOY1QUdkbTSmgmivN/s8l2Ai0aIvyiNwRzToiYWFT+vFfe/W89/BesSfuCDE7Wmgl+R1eOQiG0mC6LFnvGOJk0qdmgV/BvPA3qe7eo8UAa/+t0lpHOEfj9+L9LAguP6GblhKEfbaiyCS2U/uguOpWWt1hwNGUYNeKYMk8bNtKsMAmZ8hFTWI2ziFJ1ctjb7Z6+XXlsKr1pUltlX87/cKBJlgFNBy04SR68/GZnm0="
    branches:
      - master
      - dev
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
      - secure: OS2t2tnwZWittCK1C5XpQv41k5zVljZPAmG8DEY1D37RemkyKcNxaXeZwa1/y7qsJZCnPZE4wGbjSE3O3RTbtHbTfb7fBfy3NO/OWjOxszFayS21780U7BSnO9W76FpRyOXZyslsN16gd3Re5FRPvYEJ8w8JvuxhecVpZ6bUUhs+t7i31iQQIpbkat6SN3MmIO+Sb69osP/N4J+dRE40Kiowyp+6pNTlww0cy/uz87R1hnOyy5Izymp2IVAoiR+nAFx6c0Z5l9nYBh5tACQ+2HH+JRuGXndvJatHQeBKw2Ewxxl+NfpG6IGv+Wd5PDnnlotP4ZHUYicx03XjGDuZWiwK01nIn11HhC7UA1ptVvlENXDXWY2EiiXVJgOtNxP+PH5BRivjUEgTBzqS9HQ5fB9HWVQeI4yTN92eN8w/dywek05PYBk04HjjnIYusvnJjzisNjeWQlD8tiQs1oMhsHJO9km1a9TW4/xaD9HDPof2UNaZDEhkXIxRNPtOKQnFajTqA4MWHIr9q8qruXAeRvhcx8gPk06JxatlN/wbQN0EictnZNQbhvCRs9j33Vk7PKNVquths61YYx2nFMKBGT3iHn4HP7Z5iHmfpkYdYdw9SROsLbxR0uxzk8hwQ/cFwEWc6cky25gZu5u8bJu3iIZo+nzcWvjkTsBVcIawlyk=
      - secure: e399COlQfloFtZ2TvMGyT74N1npEz2XR6tpTnkJoQf4x7orRZJf2Hq8gBJupZMHs2VUd8SmE8EEVZ+i/Sj/dxnmxvc6whL5dINae5pEDoutozAMuTofDHfHKHGZY4d5YXMdHh60Tirb1xzQh8geNESdzStqwG5L+JJfU9ynzaRIiM7vgz7GCZpqR1UIL3oBNSqTB+Dijz7TjUjTCdCGWb1KW6qF9bUOdjULVNbAux42NkLh5I26swDxEo++7mceXMJ1tJIxTsoTyLW3zOslD2OpuTDtsDVVWC+9jPhxHkzcbNLkrMHyXkVHRJ8GnVqJdqHYSQTRlEXfBuJMoDcANE2+LW3771FgMkjQuiBPFDtm8g2mcyk11p7zyPyjhf5QqcvjO8X0emEHryW2hnWc49RQQoRNQt5UjZFXRcBJ1HXq4YzY/CzYow5H9uoqEod0w5AlP4HaWHLAlh2KDmdIZ/u+VUU/ugTftW++u5tZz2Hl9cjZf5fevqXF13hr934he2AW+SRnFTlLos+5MAHwvLmT5MICfklOqtwWwwGTa/l5rJBOm0ZpZdCNzU2vHiH46eLsKla4jA6NMGeilOlVVdyBmxQNPy4VJTkXEm+XFvLmBeO1UU3WA3+/bitHckG5bpgWwo5FjVdYdSeDIzGnU/GOLlwdELB0obJsSXoT0LoY=
node_js:
- '8'
branches:
  only:
  - master
  - dev
before_install:
- rm -rf node_modules
- bash ./tools/scripts/test-latest-versions.sh
before_script:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 3000x1200x16"
- sleep 3
script:
- bash ./tools/scripts/validation.sh
- sonar-scanner
env:
  global:
  - ENCRYPTION_LABEL: d9215e5535f8
  - COMMIT_AUTHOR_EMAIL: travis@hcuge.ch
before_deploy:
- cd dist
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: qW5srlnj3UiSkQGwUv07NfyQ18Ry9emfqUXKroDuRr7q5Ip5GJ3DUGoJYJLRehHjT98YSHwUBhW9VvEgI4SopX8SMr4mPyRqU/uUL8IAcJH3kgzsBD2laDf/MPraGHOD3vg4ILZDjMWZaRmfAp2Wr2316OWiTEYGRyK7SmYH5FjLiV6NT1Iif11kRCfZKTb7HXzkldJ8kQ2zocLmihURGobRo7E4eMeYlqA+KNQkzMxcYf1SaJW8uYbWlhDY3DhyBTtMZUUV9qcH4nJ0lVGqlVpaR/+FM53pDRNlViqFZJTpvfYD8kArBjz4XF3memzd5OoG3S5+ZtjYJcUDcRPHJHqugGYFilMSdfzgol28HQlgDCaTTmA2ISOEYkxMhyqBL6LzzoHKC386eA2UbZFWYbRqx1RadDFJjAerLP4VLrOrDZOIOtrORHuFUXE8qmKW5ECSpb4W3bT3QuUr6qePTZ3jIcq31jfP317sWAjEYMMDZF4EykeaGTv6smaGdXyq5byjnfXCwzQzV8OPOwYNGTMnzWuEEU5hK/URWW1XzShxtSsnvMXP+JP8oYdJl83xSmNQJgs3aradk6LL6uI3VDcz9qnbNBJeW/uUCLBU/xPaEO65WtLeG54QbKA8oxjueRWmIAg/hiYm/N+vQaPV5mqN57D1r80b85HBgybMvfs=
  on:
    repo: DSI-HUG/dejajs-components
    branch: master
after_deploy:
- cd ..
- bash ./tools/scripts/tag.sh
- bash ./tools/scripts/deploy.sh
after_failure:
- bash ./tools/scripts/logs.sh
after_success:
- bash ./tools/scripts/logs.sh
