language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
branches:
  only:
    - master
    - travis-test
before_script:
  - npm prune
after_success:
  - npm run build:prod
  - npm run deploy
  - npm run publish