language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: true
node_js:
- '6'
branches:
  only:
  - master
  - travis-test
before_script:
- npm prune
after_success:
- git config --global user.email "remy.trompier@gmail.com"
- git config --global user.name "rtrompier"
- npm run deploy
before_install:
- openssl aes-256-cbc -K $encrypted_d9215e5535f8_key -iv $encrypted_d9215e5535f8_iv
  -in id_rsa.enc -out id_rsa -d
