import { IEditorLanguage } from './editor-language.model';
import { IEditorScrollbarOptions } from './editor-scrollbar-options';
import { IEditorTheme } from './editor-theme.component';
export declare class IEditorOptions {
    experimentalScreenReader?: boolean;
    ariaLabel?: string;
    rulers?: number[];
    wordSeparators?: string;
    selectionClipboard?: boolean;
    lineNumbers?: boolean;
    selectOnLineNumbers?: boolean;
    lineNumbersMinChars?: number;
    glyphMargin?: boolean;
    lineDecorationsWidth?: number;
    revealHorizontalRightPadding?: number;
    roundedSelection?: boolean;
    theme?: IEditorTheme;
    readOnly?: boolean;
    scrollbar?: IEditorScrollbarOptions;
    overviewRulerLanes?: number;
    cursorBlinking?: string;
    mouseWheelZoom?: boolean;
    cursorStyle?: string;
    fontLigatures?: boolean;
    disableTranslate3d?: boolean;
    hideCursorInOverviewRuler?: boolean;
    scrollBeyondLastLine?: boolean;
    automaticLayout?: boolean;
    wrappingColumn?: number;
    wordWrap?: boolean;
    wrappingIndent?: string;
    wordWrapBreakBeforeCharacters?: string;
    wordWrapBreakAfterCharacters?: string;
    wordWrapBreakObtrusiveCharacters?: string;
    stopRenderingLineAfter?: number;
    hover?: boolean;
    contextmenu?: boolean;
    mouseWheelScrollSensitivity?: number;
    quickSuggestions?: boolean;
    quickSuggestionsDelay?: number;
    parameterHints?: boolean;
    iconsInSuggestions?: boolean;
    autoClosingBrackets?: boolean;
    formatOnType?: boolean;
    suggestOnTriggerCharacters?: boolean;
    acceptSuggestionOnEnter?: boolean;
    snippetSuggestions?: 'top' | 'bottom' | 'inline' | 'none';
    tabCompletion?: boolean;
    wordBasedSuggestions?: boolean;
    selectionHighlight?: boolean;
    codeLens?: boolean;
    folding?: boolean;
    renderWhitespace?: 'none' | 'boundary' | 'all';
    renderControlCharacters?: boolean;
    renderIndentGuides?: boolean;
    renderLineHighlight?: boolean;
    useTabStops?: boolean;
    fontFamily?: string;
    fontWeight?: 'normal' | 'bold' | 'bolder' | 'lighter' | 'initial' | 'inherit' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900';
    fontSize?: number;
    lineHeight?: number;
    formatOnPaste?: boolean;
    value: string;
    language: IEditorLanguage;
}
