import { ElementRef, EventEmitter } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Color } from '../../common/core/graphics/index';
export declare class DejaColorSelectorComponent implements ControlValueAccessor {
    private static indexAttribute;
    colorhover: EventEmitter<{}>;
    private _value;
    protected onTouchedCallback: () => void;
    protected onChangeCallback: (_: any) => void;
    private _colors$;
    private _colorFabs;
    private _subColorFabs;
    private _selectedBaseIndex;
    private _selectedSubIndex;
    private _disabled;
    private colorFabs$;
    private selectedBaseIndex$;
    private subColorFabs$;
    private selectedSubIndex$;
    private hilightedBaseIndex;
    private hilightedBaseIndex$;
    private hilightedSubIndex;
    private hilightedSubIndex$;
    constructor(elementRef: ElementRef);
    disabled: boolean;
    colors: Color[];
    selectedColor: Color;
    value: Color;
    writeValue(value: Color): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
}
