import { ChangeDetectorRef, ElementRef, EventEmitter, OnInit } from '@angular/core';
import { DaysOfWeek, DejaDateSelectorComponent } from '../date-selector';
export declare class DejaDatePickerComponent implements OnInit {
    private elementRef;
    private changeDetectorRef;
    dateMax: Date;
    dateMin: Date;
    dropdownContainerId: string;
    dropdownAlignment: string;
    ownerAlignment: string;
    format: string;
    placeholder: string;
    disableDates: Array<DaysOfWeek | Date>;
    dateSelectorComponent: DejaDateSelectorComponent;
    dateChange: EventEmitter<{}>;
    protected mdHint: any;
    private inputElementRef;
    private _showDropDown;
    private keyDownSubscription;
    private _disabled;
    private _time;
    private date;
    private inputModel;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(elementRef: ElementRef, changeDetectorRef: ChangeDetectorRef);
    ngOnInit(): void;
    private readonly containerElement;
    private showDropDown;
    disabled: boolean | string;
    time: boolean | string;
    close(): void;
    open(): void;
    value: Date;
    writeValue(value: Date): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setFocus(): void;
    protected toggleDateSelector(event: Event): boolean;
    protected onDateChange(newDate: Date): void;
    protected updateModel(date: string | Date): void;
    protected reset(): void;
}
