import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import 'rxjs/Rx';
import { DaysOfWeek, DejaDateSelectorComponent } from '../date-selector';
export declare class DejaDatePickerComponent implements OnInit {
    private elementRef;
    dateMax: Date;
    dateMin: Date;
    dropdownContainerId: string;
    dropdownAlignment: string;
    ownerAlignment: string;
    format: string;
    placeholder: string;
    disableDates: Array<DaysOfWeek | Date>;
    dateSelectorComponent: DejaDateSelectorComponent;
    dateChange: EventEmitter<{}>;
    protected mdHint: any;
    private inputElementRef;
    private _useDropDown;
    private keydown;
    private keyDownSubscription;
    private _disabled;
    private _time;
    private date;
    private inputModel;
    private onTouchedCallback;
    private onChangeCallback;
    constructor(elementRef: ElementRef);
    ngOnInit(): void;
    private readonly containerElement;
    private useDropDown;
    disabled: boolean;
    time: boolean;
    close(): void;
    open(): void;
    value: Date;
    writeValue(value: Date): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    protected toggleDateSelector(event: Event): boolean;
    protected onDateChange(event: Date): void;
    protected updateModel(date: string | Date): void;
    protected reset(): void;
}
