import { ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, OnDestroy, Renderer, SimpleChanges } from '@angular/core';
import { SplitAreaDirective } from './split-area.directive';
export declare class DejaSplitterComponent implements OnChanges, OnDestroy {
    private cdRef;
    private elementRef;
    private renderer;
    direction: string;
    width: number;
    height: number;
    gutterSize: number;
    disabled: boolean;
    dragStart: EventEmitter<number[]>;
    dragProgress: EventEmitter<number[]>;
    dragEnd: EventEmitter<number[]>;
    readonly styleFlexDirection: string;
    readonly styleWidth: string;
    readonly styleHeight: string;
    private readonly nbGutters;
    private minPercent;
    private areas;
    private isDragging;
    private containerSize;
    private areaASize;
    private areaBSize;
    private eventsDragFct;
    constructor(cdRef: ChangeDetectorRef, elementRef: ElementRef, renderer: Renderer);
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    addArea(component: SplitAreaDirective, orderUser: number | null, sizeUser: number | null, minPixel: number): void;
    updateArea(component: SplitAreaDirective, orderUser: number | null, sizeUser: number | null, minPixel: number): void;
    removeArea(area: SplitAreaDirective): void;
    startDragging(startEvent: MouseEvent, gutterOrder: number): void;
    private refresh();
    private refreshStyleSizes();
    private dragEvent(event, start, areaA, areaB);
    private drag(start, end, areaA, areaB);
    private stopDragging();
    private notify(type);
}
