import { ChangeDetectorRef, ElementRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Observable } from 'rxjs/Rx';
import { IItemBase, ItemListBase, ItemListService, IViewListResult, ViewportMode } from '../../common/core/item-list';
export declare class DejaSelectComponent extends ItemListBase implements ControlValueAccessor {
    private changeDetectorRef;
    private elementRef;
    placeholder: string;
    minlength: number;
    query: string;
    maxHeight: number;
    dropdownContainerId: string;
    dropdownAlignment: string;
    itemTemplateExternal: any;
    parentItemTemplateExternal: any;
    placeHolderTemplateExternal: any;
    hintTemplateExternal: any;
    delaySearchTrigger: number;
    protected onTouchedCallback: () => void;
    protected onChangeCallback: (_: any) => void;
    protected hintTemplateInternal: any;
    protected placeHolderTemplateInternal: any;
    protected itemTemplateInternal: any;
    protected parentItemTemplateInternal: any;
    protected selectedTemplate: any;
    protected mdSuffix: any;
    private inputElementRef;
    private dropdownItemElements;
    private listcontainer;
    private dropDownComponent;
    private _type;
    private ignoreNextScrollEvents;
    private selectingItemIndex;
    private _keyboardNavigation;
    private keyboardNavigationPos;
    private keepExistingViewPort;
    private dropDownQuery;
    private filterExpression;
    private dropdownVisible;
    private lastScrollPosition;
    private _selectionClearable;
    private _waiter;
    private mouseMoveObs;
    private mouseUpObs;
    private clearFilterExpression$;
    private filterListComplete$;
    private storeScrollPosition$;
    private hideDropDown$;
    private showDropDown$;
    constructor(changeDetectorRef: ChangeDetectorRef, elementRef: ElementRef);
    selectionClearable: boolean;
    hideSelected: any;
    currentItem: IItemBase;
    pageSize: number;
    hintLabel: string;
    viewPortRowHeight: number;
    viewportMode: ViewportMode;
    childrenField: string;
    textField: string;
    valueField: string;
    searchField: string;
    type: any;
    selectingItem: (item: any) => Promise<any>;
    unselectingItem: (item: any) => Promise<any>;
    readonly isReadOnly: boolean;
    readonly isAutocomplete: boolean;
    readonly selectedItems: IItemBase[];
    itemListService: ItemListService;
    waiter: boolean;
    items: IItemBase[] | Promise<IItemBase[]> | Observable<IItemBase[]>;
    models: any[] | Observable<any[]>;
    readonly depthMax: number;
    private readonly placeHolderTemplate;
    private readonly itemTemplate;
    private readonly hintTemplate;
    private readonly parentItemTemplate;
    private readonly containerElement;
    private readonly listElement;
    private readonly inputElement;
    private keyboardNavigation;
    writeValue(value: any): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    toggleAll(): Promise<void>;
    toggleCollapse(index: number, collapsed: boolean): Promise<boolean>;
    protected filter(event: KeyboardEvent): boolean;
    protected scroll(): void;
    protected click(event: any): void;
    protected mousedown(e: MouseEvent): void;
    protected focus(event: any): void;
    protected blur(): void;
    protected queryChanged(event: Event): void;
    protected removeSelection(event: Event, item: IItemBase): boolean;
    protected calcViewPort(): Promise<IViewListResult>;
    protected ensureItemVisible(item: IItemBase | number): void;
    private onModelChange(items?);
    private mouseUp;
    private select(item, hideDropDown?);
    private toggleDropDown();
    private hideDropDown();
    private showDropDown();
    private reshowDropDown();
}
