import { AfterViewInit, ElementRef, EventEmitter, OnDestroy, OnInit } from '@angular/core';
export declare class DejaSnackbarComponent implements OnInit, AfterViewInit, OnDestroy {
    private elementRef;
    private static instances;
    delay: number;
    duration: number;
    outerContainerElement: HTMLElement;
    onAnimationDone: EventEmitter<any>;
    private host;
    private height;
    private marginTop;
    private timestamp;
    private enterAnimationDuration;
    private leaveAnimationDuration;
    private adaptAnimationDuration;
    private anchor;
    private alignents;
    private animate$;
    alignment: string;
    constructor(elementRef: ElementRef);
    onResize(): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    protected animationDone(event: Event): void;
    protected increaseElevation(): void;
    protected decreaseElevation(): void;
    private computePosition();
    private setPosition();
    private setNewWidth();
    private launchAdaptAnimation(height);
    private launchEnterAnimation();
    private launchLeaveAnimation();
}
