name: Test

on:
  push:
    branches:
      - master

jobs:
  ci_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Merge master into develop
        uses: devmasx/merge-branch@master
        with:
          label_name: 'merge branch master of github.com:DSI-HUG/dejajs-components into develop [skip ci]'
          target_branch: 'develop'
          github_token: ${{ github.token }}
