name: Publish

on:
  push:
    branches:
      - develop
      - master

jobs:
  ci_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build:lib

      - name: Lint
        run: npm run lint

      - name: Semantic Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: dsi-hug-bot
          GIT_AUTHOR_EMAIL: dsi-hug-github@hcuge.ch
          GIT_COMMITTER_NAME: dsi-hug-bot
          GIT_COMMITTER_EMAIL: dsi-hug-github@hcuge.ch
        run: npm run release:ci

      - name: Merge release back to develop
        if: github.ref == 'refs/heads/master'
        uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.DSI_HUG_BOT_GITHUB_TOKEN }}
          source_ref: 'master'
          target_branch: 'develop'
          commit_message_template: 'merge branch {source_ref} of github.com:DSI-HUG/dejajs-components into {target_branch} [skip ci]'
