name: Publish library to NPM

on:
  push:
    branches:
        - master
        - develop
        - next/13.x.x
        - release/13.x.x
    tags-ignore:
        - skip-ci
  release:

jobs:
  ci_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build:lib
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Semantic Release
        run: npx semantic-release
        env:
            GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish ./dist --access public
