name: CI tests

on:
  pull_request:
      branches:
        - next/13.x.x
        - release/13.x.x

jobs:
  ci_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Make sure npm is latest
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Lint
        run: npm run build:lib
      - name: license-check
        run: npm run license-check
      - name: Test
        run: npm run test:lib:ci
